//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Updater.rc
//
#define IDR_MANIFEST                    1
#define IDM_ABOUTBOX                    0x0010
#define IDD_FULL_PROPPAGE_DOWNLOAD      101
#define IDD_FULL_PROPPAGE_INSTALL       102
#define IDD_FULL_PROPPAGE_WELCOME       103
#define IDD_FULL_PROPPAGE_FINISH        104
#define IDD_FULL_PROPPAGE_CHECK         105
#define IDI_UPDATER                     106
#define IDD_SILENT                      107
#define IDD_FULL_PROPPAGE_ROLLBACK      108
#define IDR_SILENT_POPUP                109
#define IDI_RESULT_ERROR                110
#define IDI_RESULT_GOOD                 111
#define IDI_CHECK1                      112
#define IDI_CHECK2                      113
#define IDI_CHECK3                      114
#define IDI_CHECK4                      115
#define IDI_CHECK5                      116
#define IDI_DOWNLOAD1                   117
#define IDI_DOWNLOAD2                   118
#define IDI_DOWNLOAD3                   119
#define IDI_DOWNLOAD4                   120
#define IDI_INSTALL1                    121
#define IDI_INSTALL2                    122
#define IDI_INSTALL3                    123
#define IDI_INSTALL4                    124
#define IDI_INSTALL5                    125
#define IDI_INSTALL6                    126
#define IDI_INSTALL7                    127
#define IDI_INSTALL8                    128
#define IDB_PROGRESS1                   129
#define IDB_PROGRESS2                   130
#define IDB_PROGRESS3                   131
#define IDB_PROGRESS4                   132
#define IDB_PROGRESS5                   133
#define IDB_LOGO_LARGE                  134
#define IDB_LOGO_SMALL                  135
#define IDC_USERHAND                    136
#define IDD_HIDDEN                      137
#define IDD_ABOUT                       138
#define IDB_ABOUT                       139
#define IDD_FULL_PROPPAGE_SELECTUPDATE  139
#define IDD_FULL_PROPPAGE_LICENSE       140
#define IDB_UPDATER                     141
#define IDB_UPDATER_NEG                 142
#define IDB_WIZARD_HEADER               143
#define IDR_UPDATERCOPY                 146
#define IDD_AUTHENTICATION              147
#define IDD_FULL_PROPPAGE_HTMLMESSAGE   148
#define IDD_CONFIRMATION_CLOSEAPP       152
#define IDD_CONFIRMATION_DELETEFILE     153
#define IDD_CONFIRMATION_STOPUPDATING   154
#define IDD_CONFIRMATION                154
#define IDB_CONFIRMATION                155
#define IDD_ERROR                       155
#define IDB_ERROR                       156
#define IDD_INFORMATION                 156
#define IDB_INFORMATION                 157
#define IDD_FULL_PROPPAGE_PROTECTION    157
#define IDD_WARNING                     158
#define IDB_WARNING                     158
#define IDD_RESTORE                     159
#define IDI_RESTORE                     160
#define IDD_PROXYSETTINGS               161
#define IDD_SELECTLANGUAGE              162
#define IDB_SELECTLANGUAGE              163
#define IDD_CRASH                       165
#define IDD_LOGVIEWER                   166
#define IDI_LOGVIEWER                   167
#define IDB_AUTHENTICATION              168
#define IDD_CLOSEAPPLICATION            170
#define IDB_CLOSEAPPLICATION            171
#define lblExplanation                  1001
#define lblStatus                       1002
#define lblTitle                        1009
#define lblFileProgress                 1010
#define prgFileProgress                 1011
#define lblFileProgressProcent          1012
#define lblTotalProgress                1013
#define prgTotalProgress                1014
#define lblTotalProgressProcent         1015
#define picLogo                         1016
#define lblFeatures                     1017
#define lblUpdaterVersion               1018
#define lblUpdater                      1019
#define btnOK                           1020
#define lblWebsite                      1021
#define lblLanguageVersion              1022
#define txtUpdaterVersion               1023
#define txtLanguageVersion              1024
#define lblHyperlink                    1025
#define lblLanguageUsed                 1026
#define txtLanguageUsed                 1027
#define lblDeveloper                    1028
#define lblSpecialThanks                1029
#define lstThanks                       1032
#define treeUpdateSelection             1033
#define lblDescriptionTitle             1034
#define lblDescription                  1035
#define txtLicense                      1036
#define rdLicenceAgree                  1037
#define rdLicenceNotAgree               1038
#define lblUsername                     1039
#define lblPassword                     1040
#define txtUsername                     1041
#define txtPassword                     1042
#define btnCancel                       1043
#define htmlMessage                     1050
#define lblFeature1                     1051
#define lblFeature2                     1052
#define lblMoreInfo                     1052
#define lblFeature3                     1053
#define lblFeature4                     1054
#define btnYes                          1054
#define lblFeature5                     1055
#define btnNo                           1055
#define lnSplitter                      1056
#define bmpLogo                         1057
#define btnMore                         1058
#define lblMore                         1059
#define lnMoreSplitter                  1060
#define chkCreateShortcuts              1060
#define lblCheckLicense                 1061
#define chkUserData                     1061
#define lblCheckFiles                   1062
#define lblGetLicense                   1063
#define btnRestore                      1067
#define lblProgress                     1068
#define prgRestore                      1070
#define btnClose                        1072
#define rdDirectConnection              1073
#define rdAutoDetect                    1074
#define rdManual                        1075
#define rdAutoConfigURL                 1076
#define txtAutoConfigURL                1077
#define lblHttpProxy                    1078
#define lblFtpProxy                     1079
#define txtHttpProxy                    1080
#define txtFtpProxy                     1081
#define chkRemember                     1082
#define cboLanguage                     1083
#define lblDetails                      1084
#define txtCrashInfo                    1085
#define chkSendErrorReport              1086
#define txtLog                          1087
#define bmpImage                        1089
#define chkSaveCredentials              1090
#define prgEnd                          1093
#define btnEndNow                       1098
#define icoApplication                  1100
#define IDS_GENERAL_OK                  10001
#define IDS_GENERAL_CANCEL              10002
#define IDS_GENERAL_YES                 10003
#define IDS_GENERAL_NO                  10004
#define IDS_GENERAL_NEXT                10005
#define IDS_GENERAL_FINISH              10006
#define IDS_GENERAL_TITLE               10007
#define IDS_QUESTION_CLOSE              10008
#define IDS_QUESTION_CLOSEAPPLICATION   10009
#define IDS_QUESTION_DELETEFILE         10010
#define IDS_QUESTIONTITLE_SURE          10011
#define IDS_SILENT_CHECKVERSION         10012
#define IDS_SILENT_DOWNLOAD             10013
#define IDS_SILENT_INSTALL              10014
#define IDS_SILENT_WELCOME              10015
#define IDS_SILENT_NOTIFICATION         10016
#define IDS_SILENT_FINISH               10017
#define IDS_SILENT_ERROR                10018
#define IDS_SILENT_ROLLBACK             10019
#define IDS_ERROR_UNKNOWN               10020
#define IDS_ERROR_NOCONNECTION          10021
#define IDS_ERROR_SERVER                10022
#define IDS_ERROR_NODISKSPACE           10023
#define IDS_ERROR_FILENOTFOUND          10024
#define IDS_ERROR_COPYFILE              10025
#define IDS_ERROR_DELETEFILE            10026
#define IDS_ERROR_RUNFILE               10027
#define IDS_ERROR_CLOSEAPP              10028
#define IDS_ERROR_FILECORRUPT           10029
#define IDS_ERROR_NONEWVERSION          10030
#define IDS_ERROR_WRITEFILE             10031
#define IDS_FULL_WELCOME_EXPLANATION    10032
#define IDS_FULL_WELCOME_TITLE          10033
#define IDS_FULL_CHECKVERSION_TITLE     10034
#define IDS_FULL_DOWNLOAD_TITLE         10035
#define IDS_FULL_INSTALL_TITLE          10036
#define IDS_FULL_FINISH_TITLE           10037
#define IDS_FULL_ROLLBACK_TITLE         10038
#define IDS_FULL_CHECKVERSION_EXPLANATION 10039
#define IDS_FULL_FILEPROGRESS           10040
#define IDS_FULL_TOTALPROGRESS          10041
#define IDS_FULL_FINISH_EXPLANATION     10042
#define IDS_FULL_DOWNLOAD_EXPLANATION   10043
#define IDS_FULL_INSTALL_EXPLANATION    10044
#define IDS_FULL_CHECKVERSION_FEATURES  10045
#define IDS_FULL_ROLLBACK_EXPLANATION   10046
#define IDS_ACTION_COPY                 10047
#define IDS_ACTION_DELETE               10048
#define IDS_ACTION_RUN                  10049
#define IDS_ACTION_REGISTRY             10050
#define IDS_ACTION_INI                  10051
#define IDS_STATUS_CONNECTINGTOSERVER   10052
#define IDS_STATUS_NONEWVERSION         10053
#define IDS_STATUS_NEWVERSION           10054
#define IDS_STATUS_INITIALIZING         10055
#define IDS_ERROR_UNZIPFILE             10056
#define IDS_ACTION_UNZIP                10057
#define IDS_ACTION_BACKUP               10058
#define IDS_ABOUT_TITLE                 10059
#define IDS_ABOUT_UPDATERVERSION        10060
#define IDS_ABOUT_DEVELOPEDBY           10061
#define IDS_ABOUT_WEBSITE               10062
#define IDS_ABOUT_LANGUAGEVERSION       10063
#define IDS_ABOUT_TRANSLATEDBY          10064
#define IDS_ABOUT_LANGUAGEUSED          10065
#define IDS_ABOUT_SPECIALTHANKS         10066
#define IDS_ABOUT_THANKS_NAME           10067
#define IDS_ABOUT_THANKS_REASON         10068
#define IDS_FULL_CHECKVERSION_SUBTITLE  10069
#define IDS_FULL_DOWNLOAD_SUBTITLE      10070
#define IDS_FULL_INSTALL_SUBTITLE       10071
#define IDS_FULL_FINISH_SUBTITLE        10072
#define IDS_FULL_ROLLBACK_SUBTITLE      10073
#define IDS_FULL_SELECTUPDATE_EXPLANATION 10074
#define IDS_FULL_SELECTUPDATE_TITLE     10075
#define IDS_FULL_SELECTUPDATE_SUBTITLE  10076
#define IDS_FULL_LICENSE_TITLE          10077
#define IDS_FULL_LICENSE_SUBTITLE       10078
#define IDS_FULL_LICENSE_AGREE          10079
#define IDS_FULL_LICENSE_NOTAGREE       10080
#define IDS_AUTHENTICATION_EXPLANATION  10081
#define IDS_AUTHENTICATION_USERNAME     10082
#define IDS_AUTHENTICATION_PASSWORD     10083
#define IDS_AUTHENTICATION_TITLE        10084
#define IDS_FULL_HTMLMESSAGE_TITLE      10085
#define IDS_FULL_HTMLMESSAGE_SUBTITLE   10086
#define IDS_FULL_SELECTUPDATE_MOREINFO  10087
#define IDS_CONFIRMATION_STOPUPDATING_TITLE 10088
#define IDS_CONFIRMATION_STOPUPDATING_EXPLANATION 10089
#define IDS_CONFIRMATION_DELETEFILE_TITLE 10090
#define IDS_CONFIRMATION_DELETEFILE_EXPLANATION 10091
#define IDS_CONFIRMATION_CLOSEAPPLICATION_TITLE 10092
#define IDS_CONFIRMATION_CLOSEAPPLICATION_EXPLANATION 10093
#define IDS_CONFIRMATION_TITLE          10094
#define IDS_ERROR_TITLE                 10095
#define IDS_ERROR_MORE                  10096
#define IDS_ERROR_UNKNOWN_TITLE         10097
#define IDS_ERROR_UNKNOWN_EXPLANATION   10098
#define IDS_ERROR_NOCONNECTION_TITLE    10099
#define IDS_ERROR_NOCONNECTION_EXPLANATION 10100
#define IDS_ERROR_NOCONNECTION_MORE     10101
#define IDS_ERROR_SERVER_TITLE          10102
#define IDS_ERROR_SERVER_EXPLANATION    10103
#define IDS_ERROR_SERVER_MORE           10104
#define IDS_ERROR_NODISKSPACE_TITLE     10105
#define IDS_ERROR_NODISKSPACE_EXPLANATION 10106
#define IDS_ERROR_NODISKSPACE_MORE      10107
#define IDS_ERROR_FILENOTFOUND_TITLE    10108
#define IDS_ERROR_FILENOTFOUND_EXPLANATION 10109
#define IDS_ERROR_FILENOTFOUND_MORE     10110
#define IDS_ERROR_COPYFILE_TITLE        10111
#define IDS_ERROR_COPYFILE_EXPLANATION  10112
#define IDS_ERROR_COPYFILE_MORE         10113
#define IDS_ERROR_DELETEFILE_TITLE      10114
#define IDS_ERROR_DELETEFILE_EXPLANATION 10115
#define IDS_ERROR_DELETEFILE_MORE       10116
#define IDS_ERROR_RUNFILE_TITLE         10117
#define IDS_ERROR_RUNFILE_EXPLANATION   10118
#define IDS_ERROR_RUNFILE_MORE          10119
#define IDS_ERROR_CLOSEAPP_TITLE        10120
#define IDS_ERROR_CLOSEAPP_EXPLANATION  10121
#define IDS_ERROR_CLOSEAPP_MORE         10122
#define IDS_ERROR_FILECORRUPT_TITLE     10123
#define IDS_ERROR_FILECORRUPT_EXPLANATION 10124
#define IDS_ERROR_FILECORRUPT_MORE      10125
#define IDS_ERROR_WRITEFILE_TITLE       10126
#define IDS_ERROR_WRITEFILE_EXPLANATION 10127
#define IDS_ERROR_WRITEFILE_MORE        10128
#define IDS_ERROR_UNZIPFILE_TITLE       10129
#define IDS_ERROR_UNZIPFILE_EXPLANATION 10130
#define IDS_ERROR_UNZIPFILE_MORE        10131
#define IDS_INFORMATION_TITLE           10132
#define IDS_INFORMATION_RESTARTSYSTEM_TITLE 10133
#define IDS_INFORMATION_RESTARTSYSTEM_EXPLANATION 10134
#define IDS_FULL_FINISH_CREATESHORTCUTS 10135
#define IDS_FULL_PROTECTION_TITLE       10136
#define IDS_FULL_PROTECTION_SUBTITLE    10137
#define IDS_FULL_PROTECTION_EXPLANATION 10138
#define IDS_FULL_PROTECTION_CHECKLICENSE 10139
#define IDS_FULL_PROTECTION_CHECKFILES  10140
#define IDS_ERROR_PROTECTION_TITLE      10141
#define IDS_ERROR_PROTECTION_EXPLANATION 10142
#define IDS_ERROR_PROTECTION_MORE       10143
#define IDS_FULL_PROTECTION_GETLICENSE  10144
#define IDS_ERROR_PROTECTION            10145
#define IDS_ACTION_REGISTER             10146
#define IDS_ACTION_SETFILEATTR          10147
#define IDS_CONFIRMATION_REGISTER_TITLE 10148
#define IDS_CONFIRMATION_REGISTER_EXPLANATION 10149
#define IDS_WARNING_REGISTER            10150
#define IDS_WARNING_TITLE               10151
#define IDS_WARNING_REGISTER_TITLE      10152
#define IDS_WARNING_REGISTER_EXPLANATION 10153
#define IDS_POPUP_BITMAPS               10154
#define IDS_RESTORE_TITLE               10155
#define IDS_RESTORE_EXPLANATION         10156
#define IDS_RESTORE_PROGRESS            10157
#define IDS_RESTORE_RESTORE             10158
#define IDS_RESTORE_CLOSE               10159
#define IDS_PROXY_TITLE                 10160
#define IDS_PROXY_DIRECT                10161
#define IDS_PROXY_AUTODETECT            10162
#define IDS_PROXY_MANUAL                10163
#define IDS_PROXY_HTTP                  10164
#define IDS_PROXY_FTP                   10165
#define IDS_PROXY_AUTOCONFIGURL         10166
#define IDS_LOGVIEWER_TITLE             10167
#define IDS_LOGVIEWER_NOLOG             10168
#define IDS_AUTHENTICATION_SAVECREDENTIALS 10169
#define IDS_CLOSEAPPLICATION_TITLE      10170
#define IDS_CLOSEAPPLICATION_EXPLANATION 10171
#define IDS_CLOSEAPPLICATION_ENDNOW     10172
#define IDS_CLOSEAPPLICATION_APPLICATION 10174
#define IDS_CONFIRMATION_CLOSEAPPLICATION_USER_EXPLANATION 10175
#define ID_SILENT_POPUP_EXIT            32771
#define ID_SILENT_POPUP_CUSTOM1         32772
#define ID_SILENT_POPUP_CUSTOM2         32773
#define ID_SILENT_POPUP_CUSTOM3         32774
#define ID_SILENT_POPUP_CUSTOM4         32775
#define ID_SILENT_POPUP_CUSTOM5         32776
#define ID_SILENT_POPUP_CUSTOM6         32777
#define ID_SILENT_POPUP_CUSTOM7         32778
#define ID_SILENT_POPUP_CUSTOM8         32779
#define ID_SILENT_POPUP_CUSTOM9         32780
#define ID_SILENT_POPUP_CUSTOM10        32781
#define ID_SILENT_POPUP_ABOUT           32783

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        172
#define _APS_NEXT_COMMAND_VALUE         32784
#define _APS_NEXT_CONTROL_VALUE         1101
#define _APS_NEXT_SYMED_VALUE           5001
#endif
#endif
